#!/bin/bash

## Disable IPv6

enable_ipv6() {
	ipv6_conf_path=/proc/sys/net/ipv6/conf;
	for device in $(ls "$ipv6_conf_path")
	do
		target_flag="$ipv6_conf_path"/"$device"/disable_ipv6
		echo "0" > $target_flag
	done
}

enable_ipv6

